/* ============================================================
 * EECS 348 Assignment 2
 * ------------------------------------------------------------
 * Program: chatgpt.c
 *
 * Description:
 *   Prioritizes a CEO's inbox using a MaxHeap implemented as a
 *   dynamically-growing, list-based (array-backed) heap. Emails
 *   are ranked first by sender category (Boss > Subordinate >
 *   Peer > ImportantPerson > everything else) and, when two
 *   emails share a category, by date (the newer email wins).
 *   Commands are read one per line from a test file or from
 *   stdin:
 *       EMAIL <sender category>,<subject>,<date> - add an email
 *       NEXT                                     - show top email
 *       READ                                     - remove top email
 *       COUNT                                    - show # unread
 *
 * Inputs:
 *   argv[1] (optional) - path to a test file of commands. If no
 *   argument is given, commands are read from standard input.
 *
 * Output:
 *   Terminal output produced by NEXT and COUNT, in the exact
 *   Sender/Subject/Date and count format shown in the handout.
 *
 * Collaborators: None
 *
 * Other sources for the code:
 *   Based on the unmodified first draft generated by ChatGPT
 *   (OpenAI), produced for comparison with a second,
 *   independently generated Gemini (Google) draft.
 *
 * Author (comments added by): Cole Nola
 * Creation date: 9/16/2026
 * Revision date: September 17, 2026
 * Revisions:
 *   - Correctness: every strcpy() call was replaced with a new
 *     safeCopy() helper that uses strncpy() and then always
 *     writes an explicit null terminator, so an over-long
 *     sender, subject, or date field can no longer overflow the
 *     struct or leave a string unterminated.
 *   - Execution time: no algorithmic change was needed. insert
 *     and remove remain O(log n) via heapifyUp/heapifyDown,
 *     which was already correct.
 *   - Space complexity: the fixed Email heap[1000] array was
 *     replaced with a dynamically-allocated array (malloc at
 *     start, realloc to double the capacity whenever it fills
 *     up), adapted from the idea behind Gemini's draft. The
 *     program now uses memory proportional to the number of
 *     emails actually inserted, with no hard cap.
 *   - Maintainability: NULL checks were added after every
 *     malloc()/realloc() call, and an explicit freeHeap()
 *     function frees all heap memory before the program exits.
 *     Prologue, block, and line-by-line comments were kept/
 *     expanded to meet the assignment's comment rubric.
 * ============================================================ */

#include <stdio.h>   /* for FILE, fopen, fgets, printf, sscanf */
#include <stdlib.h>  /* for malloc, realloc, free, exit */
#include <string.h>  /* for strcmp, strncpy, strtok, strcspn, strncmp */

/* Starting capacity of the heap's underlying array. It grows
   automatically (doubling) whenever it fills up, so this is just
   a reasonable initial size, not a hard maximum. */
#define INITIAL_CAPACITY 16

/* ------------------------------------------------------------
 * Email
 *   One email message.
 *   sender   - sender CATEGORY string (e.g., "Boss")
 *   subject  - subject line (may contain spaces, not commas)
 *   date     - date string in MM-DD-YYYY format
 *   priority - numeric priority derived from "sender"
 * ------------------------------------------------------------ */
typedef struct {
    char sender[30];
    char subject[200];
    char date[11];
    int priority;
} Email;

/* ------------------------------------------------------------
 * MaxHeap
 *   A list-based (array-based) max-heap of Email records, using
 *   a dynamically-allocated array that grows as more emails
 *   arrive.
 *   emails   - pointer to a dynamically-allocated array of Email
 *   size     - number of emails currently stored
 *   capacity - number of Email slots currently allocated
 * ------------------------------------------------------------ */
typedef struct {
    Email *emails;
    int size;
    int capacity;
} MaxHeap;

/* ------------------------------------------------------------
 * getPriority
 *   Maps a sender category string to a numeric priority score.
 * Input:  sender - the sender category string from the EMAIL line
 * Output: an integer priority from 1 (lowest) to 5 (highest)
 * ------------------------------------------------------------ */
int getPriority(char sender[]) {
    if (strcmp(sender, "Boss") == 0)
        /* Boss must be read first: highest score. */
        return 5;
    else if (strcmp(sender, "Subordinate") == 0)
        /* Subordinate is read next. */
        return 4;
    else if (strcmp(sender, "Peer") == 0)
        /* Peer is read after Subordinate. */
        return 3;
    else if (strcmp(sender, "ImportantPerson") == 0)
        /* ImportantPerson is read after Peer. */
        return 2;
    else
        /* Anything else (including "OtherPerson") is read last. */
        return 1;
}

/* ------------------------------------------------------------
 * dateValue
 *   Converts an MM-DD-YYYY date string into a YYYYMMDD integer
 *   so two dates can be compared with a simple > check.
 * Input:  date - date string in MM-DD-YYYY format
 * Output: integer YYYYMMDD representation of the date
 * ------------------------------------------------------------ */
int dateValue(char date[]) {
    int month, day, year;

    /* Pull the three numeric fields out of "MM-DD-YYYY". */
    sscanf(date, "%d-%d-%d", &month, &day, &year);

    /* Combine into one comparable integer, year first, so later
       years always sort higher regardless of month/day. */
    return year * 10000 + month * 100 + day;
}

/* ------------------------------------------------------------
 * higherPriority
 *   Decides whether email "a" should be read before email "b".
 * Input:  a, b - the two emails being compared
 * Output: 1 (true) if a should be read before b, 0 otherwise
 * ------------------------------------------------------------ */
int higherPriority(Email a, Email b) {
    if (a.priority != b.priority)
        /* Different categories: bigger priority number wins. */
        return a.priority > b.priority;

    /* Same category: fall back to comparing dates, newer first. */
    return dateValue(a.date) > dateValue(b.date);
}

/* ------------------------------------------------------------
 * swap
 *   Exchanges the contents of two Email structs in place.
 * ------------------------------------------------------------ */
void swap(Email *a, Email *b) {
    Email temp = *a;  /* stash a's value */
    *a = *b;           /* copy b's value into a */
    *b = temp;          /* copy the stashed original a into b */
}

/* ------------------------------------------------------------
 * createHeap
 *   Allocates a new, empty MaxHeap with room for
 *   INITIAL_CAPACITY emails. The array grows later via
 *   resizeIfNeeded() as more emails are inserted. Exits the
 *   program with an error message if either allocation fails.
 * Output: pointer to a heap-allocated MaxHeap
 * ------------------------------------------------------------ */
MaxHeap *createHeap(void) {
    /* Allocate the MaxHeap struct itself. */
    MaxHeap *heap = (MaxHeap *)malloc(sizeof(MaxHeap));
    if (heap == NULL) {
        /* Allocation failed; nothing more we can do. */
        fprintf(stderr, "Error: could not allocate heap.\n");
        exit(1);
    }

    heap->size = 0;                       /* heap starts empty */
    heap->capacity = INITIAL_CAPACITY;    /* starting room */
    /* Allocate the backing array for the emails themselves. */
    heap->emails = (Email *)malloc(sizeof(Email) * heap->capacity);
    if (heap->emails == NULL) {
        fprintf(stderr, "Error: could not allocate email array.\n");
        free(heap);
        exit(1);
    }

    return heap;
}

/* ------------------------------------------------------------
 * resizeIfNeeded
 *   Doubles the heap's backing array whenever it becomes full,
 *   so the number of emails the program can hold is not capped
 *   at a fixed constant. Exits the program with an error
 *   message if growing the array fails.
 * ------------------------------------------------------------ */
void resizeIfNeeded(MaxHeap *heap) {
    Email *bigger;

    /* Only grow once the array is completely full. */
    if (heap->size < heap->capacity)
        return;

    heap->capacity *= 2;  /* double the capacity */
    bigger = (Email *)realloc(heap->emails, sizeof(Email) * heap->capacity);
    if (bigger == NULL) {
        fprintf(stderr, "Error: could not grow email array.\n");
        exit(1);
    }
    heap->emails = bigger;  /* keep the (possibly moved) new block */
}

/* ------------------------------------------------------------
 * heapifyUp
 *   Restores the max-heap property by moving the email at
 *   "index" upward until its parent outranks (or ties) it.
 *   Called right after a new email is appended to the array.
 * ------------------------------------------------------------ */
void heapifyUp(MaxHeap *heap, int index) {
    int parent;

    while (index > 0) {
        parent = (index - 1) / 2;  /* array-based parent formula */

        if (higherPriority(heap->emails[index], heap->emails[parent])) {
            /* Child outranks its parent: swap and keep climbing. */
            swap(&heap->emails[index], &heap->emails[parent]);
            index = parent;
        } else {
            /* Heap property holds; stop climbing. */
            break;
        }
    }
}

/* ------------------------------------------------------------
 * heapifyDown
 *   Restores the max-heap property by moving the email at
 *   "index" downward, swapping with the higher-priority child,
 *   until neither child outranks it. Called after removal.
 * ------------------------------------------------------------ */
void heapifyDown(MaxHeap *heap, int index) {
    int left, right, largest;

    while (1) {
        left = 2 * index + 1;   /* array-based left-child formula */
        right = 2 * index + 2;  /* array-based right-child formula */
        largest = index;         /* assume current node wins for now */

        if (left < heap->size &&
            higherPriority(heap->emails[left], heap->emails[largest])) {
            /* Left child actually outranks the current node. */
            largest = left;
        }

        if (right < heap->size &&
            higherPriority(heap->emails[right], heap->emails[largest])) {
            /* Right child outranks whichever node is winning so far. */
            largest = right;
        }

        if (largest != index) {
            /* A child outranked the parent: swap down and keep sinking. */
            swap(&heap->emails[index], &heap->emails[largest]);
            index = largest;
        } else {
            /* Heap property holds; stop sinking. */
            break;
        }
    }
}

/* ------------------------------------------------------------
 * insert
 *   Adds a new email to the heap: grow the array first if
 *   necessary, place it at the next free slot, then bubble it
 *   up to its correct position.
 * ------------------------------------------------------------ */
void insert(MaxHeap *heap, Email email) {
    resizeIfNeeded(heap);              /* make room if the array is full */
    heap->emails[heap->size] = email;  /* place email at the end */
    heapifyUp(heap, heap->size);       /* restore heap order */
    heap->size++;                      /* one more email is now stored */
}

/* ------------------------------------------------------------
 * removeMax
 *   Removes and discards the highest-priority (root) email.
 *   Does nothing if the heap is already empty.
 * ------------------------------------------------------------ */
void removeMax(MaxHeap *heap) {
    if (heap->size == 0)
        return;  /* nothing to remove */

    /* Move the last email into the root, then shrink the heap
       by one and sink the new root down to its proper place. */
    heap->emails[0] = heap->emails[heap->size - 1];
    heap->size--;

    if (heap->size > 0)
        heapifyDown(heap, 0);
}

/* ------------------------------------------------------------
 * nextEmail
 *   Prints the highest-priority email (the root) without
 *   removing it. Prints nothing if the heap is empty.
 * ------------------------------------------------------------ */
void nextEmail(MaxHeap *heap) {
    if (heap->size == 0)
        /* Nothing to show. */
        return;

    printf("Next email:\n");
    printf("Sender: %s\n", heap->emails[0].sender);
    printf("Subject: %s\n", heap->emails[0].subject);
    printf("Date: %s\n", heap->emails[0].date);
}

/* ------------------------------------------------------------
 * freeHeap
 *   Releases all memory owned by the heap (the email array and
 *   the MaxHeap struct itself).
 * ------------------------------------------------------------ */
void freeHeap(MaxHeap *heap) {
    free(heap->emails);  /* free the array of emails */
    free(heap);           /* free the heap struct */
}

/* ------------------------------------------------------------
 * safeCopy
 *   Copies "src" into fixed-size buffer "dest" (of size
 *   destSize) without ever writing past the end of dest, and
 *   always leaves dest null-terminated. This replaces the
 *   unchecked strcpy() calls used in the original draft, which
 *   could overflow the sender/subject/date fields if the input
 *   file contained an unexpectedly long value.
 * ------------------------------------------------------------ */
void safeCopy(char *dest, const char *src, size_t destSize) {
    strncpy(dest, src, destSize - 1);  /* copy at most destSize-1 chars */
    dest[destSize - 1] = '\0';         /* guarantee a null terminator */
}

/* ------------------------------------------------------------
 * main
 *   Reads commands from a file (argv[1]) or stdin, one per
 *   line, and dispatches each to the matching heap operation.
 * ------------------------------------------------------------ */
int main(int argc, char *argv[]) {
    MaxHeap *heap = createHeap();  /* start with an empty heap */
    FILE *file;
    char line[300];  /* buffer for one line of input */

    /* Use the file named on the command line if one was given;
       otherwise fall back to reading from standard input. */
    if (argc > 1)
        file = fopen(argv[1], "r");
    else
        file = stdin;

    if (file == NULL) {
        /* The named file could not be opened; bail out. */
        printf("Could not open file.\n");
        freeHeap(heap);
        return 1;
    }

    /* Process the input one line at a time until end of file. */
    while (fgets(line, sizeof(line), file) != NULL) {

        /* Strip the trailing newline so string comparisons work. */
        line[strcspn(line, "\n")] = '\0';

        /* EMAIL command */
        if (strncmp(line, "EMAIL ", 6) == 0) {
            Email email;

            char *data = line + 6;  /* skip past "EMAIL " */

            /* Split the remaining text on commas into its three
               fields: sender category, subject, and date. */
            char *sender = strtok(data, ",");
            char *subject = strtok(NULL, ",");
            char *date = strtok(NULL, ",");

            if (sender != NULL && subject != NULL && date != NULL) {
                /* Bounds-checked copies into the fixed-size
                   struct buffers; safeCopy() always leaves the
                   destination null-terminated. */
                safeCopy(email.sender, sender, sizeof(email.sender));
                safeCopy(email.subject, subject, sizeof(email.subject));
                safeCopy(email.date, date, sizeof(email.date));

                email.priority = getPriority(email.sender);

                insert(heap, email);
            }
        }

        /* NEXT command */
        else if (strcmp(line, "NEXT") == 0) {
            nextEmail(heap);
        }

        /* READ command */
        else if (strcmp(line, "READ") == 0) {
            removeMax(heap);
        }

        /* COUNT command */
        else if (strcmp(line, "COUNT") == 0) {
            printf("There are %d emails to read.\n", heap->size);
        }
        /* Any other line is silently ignored. */
    }

    /* Only close the file if we actually opened one (not stdin). */
    if (file != stdin)
        fclose(file);

    freeHeap(heap);  /* release all heap memory before exiting */
    return 0;
}