/* ============================================================
 * EECS 348 Assignment 2
 * ------------------------------------------------------------
 * Program: chatgpt.c - CEO Email Priority Queue (ChatGPT draft)
 *
 * Description:
 *   Prioritizes a CEO's inbox using a MaxHeap implemented as a
 *   fixed-size, list-based (array-backed) heap. Emails are
 *   ranked first by sender category (Boss > Subordinate > Peer
 *   > ImportantPerson > everything else) and, when two emails
 *   share a category, by date (the newer email wins). Commands
 *   are read one per line from a test file or from stdin:
 *       EMAIL <sender category>,<subject>,<date> - add an email
 *       NEXT                                     - show top email
 *       READ                                     - remove top email
 *       COUNT                                    - show # unread
 *
 * Inputs:
 *   argv[1] (optional) - path to a test file of commands. If no
 *   argument is given, commands are read from standard input.
 *
 * Output:
 *   Terminal output produced by NEXT and COUNT, in the exact
 *   Sender/Subject/Date and count format shown in the handout.
 *
 * Collaborators: None
 *
 * Other sources for the code:
 *   This file is the unmodified first draft generated by
 *   ChatGPT (OpenAI), produced for comparison with a second,
 *   independently generated Gemini (Google) draft.
 *
 * Author (comments added by): Cole Nola
 * Creation date: 9/16/2026
 * Revision date: September 17, 2026
 * ============================================================ */

#include <stdio.h>   /* for FILE, fopen, fgets, printf, sscanf */
#include <stdlib.h>  /* included by the original draft (unused directly) */
#include <string.h>  /* for strcmp, strcpy, strtok, strcspn, strncmp */

/* Hard cap on the number of emails the heap can ever hold. The
   backing array below is sized to this constant at compile time. */
#define MAX_EMAILS 1000

/* ------------------------------------------------------------
 * Email
 *   One email message.
 *   sender   - sender CATEGORY string (e.g., "Boss")
 *   subject  - subject line (may contain spaces, not commas)
 *   date     - date string in MM-DD-YYYY format
 *   priority - numeric priority derived from "sender"
 * ------------------------------------------------------------ */
typedef struct {
    char sender[30];
    char subject[200];
    char date[11];
    int priority;
} Email;

/* ------------------------------------------------------------
 * MaxHeap
 *   A list-based (array-based) max-heap of Email records, using
 *   a fixed-size array embedded directly in the struct.
 *   heap - fixed array of up to MAX_EMAILS Email slots
 *   size - number of emails currently stored
 * ------------------------------------------------------------ */
typedef struct {
    Email heap[MAX_EMAILS];
    int size;
} MaxHeap;

/* Get priority based on sender category */
/* ------------------------------------------------------------
 * getPriority
 *   Maps a sender category string to a numeric priority score.
 * Input:  sender - the sender category string from the EMAIL line
 * Output: an integer priority from 1 (lowest) to 5 (highest)
 * ------------------------------------------------------------ */
int getPriority(char sender[]) {
    if (strcmp(sender, "Boss") == 0)
        /* Boss must be read first: highest score. */
        return 5;
    else if (strcmp(sender, "Subordinate") == 0)
        /* Subordinate is read next. */
        return 4;
    else if (strcmp(sender, "Peer") == 0)
        /* Peer is read after Subordinate. */
        return 3;
    else if (strcmp(sender, "ImportantPerson") == 0)
        /* ImportantPerson is read after Peer. */
        return 2;
    else
        /* Anything else (including "OtherPerson") is read last. */
        return 1;
}

/* Convert date to a number so newer dates are larger */
/* ------------------------------------------------------------
 * dateValue
 *   Converts an MM-DD-YYYY date string into a YYYYMMDD integer
 *   so two dates can be compared with a simple > check.
 * Input:  date - date string in MM-DD-YYYY format
 * Output: integer YYYYMMDD representation of the date
 * ------------------------------------------------------------ */
int dateValue(char date[]) {
    int month, day, year;

    /* Pull the three numeric fields out of "MM-DD-YYYY". */
    sscanf(date, "%d-%d-%d", &month, &day, &year);

    /* Combine into one comparable integer, year first, so later
       years always sort higher regardless of month/day. */
    return year * 10000 + month * 100 + day;
}

/* Determine if email a has higher priority than email b */
/* ------------------------------------------------------------
 * higherPriority
 *   Decides whether email "a" should be read before email "b".
 * Input:  a, b - the two emails being compared
 * Output: 1 (true) if a should be read before b, 0 otherwise
 * ------------------------------------------------------------ */
int higherPriority(Email a, Email b) {
    if (a.priority != b.priority)
        /* Different categories: bigger priority number wins. */
        return a.priority > b.priority;

    /* Same category: fall back to comparing dates, newer first. */
    return dateValue(a.date) > dateValue(b.date);
}

/* Swap two emails */
/* ------------------------------------------------------------
 * swap
 *   Exchanges the contents of two Email structs in place.
 * ------------------------------------------------------------ */
void swap(Email *a, Email *b) {
    Email temp = *a;  /* stash a's value */
    *a = *b;           /* copy b's value into a */
    *b = temp;          /* copy the stashed original a into b */
}

/* Move an email upward in the heap */
/* ------------------------------------------------------------
 * heapifyUp
 *   Restores the max-heap property by moving the email at
 *   "index" upward until its parent outranks (or ties) it.
 *   Called right after a new email is appended to the array.
 * ------------------------------------------------------------ */
void heapifyUp(MaxHeap *heap, int index) {
    int parent;

    while (index > 0) {
        parent = (index - 1) / 2;  /* array-based parent formula */

        if (higherPriority(heap->heap[index], heap->heap[parent])) {
            /* Child outranks its parent: swap and keep climbing. */
            swap(&heap->heap[index], &heap->heap[parent]);
            index = parent;
        } else {
            /* Heap property holds; stop climbing. */
            break;
        }
    }
}

/* Move an email downward in the heap */
/* ------------------------------------------------------------
 * heapifyDown
 *   Restores the max-heap property by moving the email at
 *   "index" downward, swapping with the higher-priority child,
 *   until neither child outranks it. Called after removal.
 * ------------------------------------------------------------ */
void heapifyDown(MaxHeap *heap, int index) {
    int left, right, largest;

    while (1) {
        left = 2 * index + 1;   /* array-based left-child formula */
        right = 2 * index + 2;  /* array-based right-child formula */
        largest = index;         /* assume current node wins for now */

        if (left < heap->size &&
            higherPriority(heap->heap[left], heap->heap[largest])) {
            /* Left child actually outranks the current node. */
            largest = left;
        }

        if (right < heap->size &&
            higherPriority(heap->heap[right], heap->heap[largest])) {
            /* Right child outranks whichever node is winning so far. */
            largest = right;
        }

        if (largest != index) {
            /* A child outranked the parent: swap down and keep sinking. */
            swap(&heap->heap[index], &heap->heap[largest]);
            index = largest;
        } else {
            /* Heap property holds; stop sinking. */
            break;
        }
    }
}

/* Add an email to the MaxHeap */
/* ------------------------------------------------------------
 * insert
 *   Adds a new email to the heap: place it at the next free
 *   slot, then bubble it up to its correct position. Silently
 *   does nothing if the fixed-size array is already full.
 * ------------------------------------------------------------ */
void insert(MaxHeap *heap, Email email) {
    if (heap->size >= MAX_EMAILS)
        /* Array is full (more than MAX_EMAILS emails); drop it. */
        return;

    heap->heap[heap->size] = email;  /* place email at the end */
    heapifyUp(heap, heap->size);      /* restore heap order */
    heap->size++;                      /* one more email is stored */
}

/* Remove the highest-priority email */
/* ------------------------------------------------------------
 * removeMax
 *   Removes and returns the highest-priority (root) email.
 *   Caller is responsible for only calling this when size > 0.
 * ------------------------------------------------------------ */
Email removeMax(MaxHeap *heap) {
    Email removed = heap->heap[0];  /* save the root to return later */

    /* Move the last email into the root, then shrink the heap. */
    heap->heap[0] = heap->heap[heap->size - 1];
    heap->size--;

    if (heap->size > 0)
        /* Sink the new root down to its correct place. */
        heapifyDown(heap, 0);

    return removed;
}

/* Display the highest-priority email without removing it */
/* ------------------------------------------------------------
 * nextEmail
 *   Prints the highest-priority email (the root) without
 *   removing it. Prints nothing if the heap is empty.
 * ------------------------------------------------------------ */
void nextEmail(MaxHeap *heap) {
    if (heap->size == 0)
        /* Nothing to show. */
        return;

    printf("Next email:\n");
    printf("Sender: %s\n", heap->heap[0].sender);
    printf("Subject: %s\n", heap->heap[0].subject);
    printf("Date: %s\n", heap->heap[0].date);
}

/* ------------------------------------------------------------
 * main
 *   Reads commands from a file (argv[1]) or stdin, one per
 *   line, and dispatches each to the matching heap operation.
 * ------------------------------------------------------------ */
int main(int argc, char *argv[]) {
    MaxHeap heap;      /* the heap lives on the stack (fixed size) */
    heap.size = 0;      /* start with an empty heap */

    FILE *file;

    /* Open the test file */
    /* Use the file named on the command line if one was given;
       otherwise fall back to reading from standard input. */
    if (argc > 1)
        file = fopen(argv[1], "r");
    else
        file = stdin;

    if (file == NULL) {
        /* The named file could not be opened; bail out. */
        printf("Could not open file.\n");
        return 1;
    }

    char line[300];  /* buffer for one line of input */

    /* Process the input one line at a time until end of file. */
    while (fgets(line, sizeof(line), file) != NULL) {

        /* Remove newline */
        /* Strip the trailing newline so string comparisons work. */
        line[strcspn(line, "\n")] = '\0';

        /* EMAIL command */
        if (strncmp(line, "EMAIL ", 6) == 0) {
            Email email;

            char *data = line + 6;  /* skip past "EMAIL " */

            /* Split the remaining text on commas into its three
               fields: sender category, subject, and date. */
            char *sender = strtok(data, ",");
            char *subject = strtok(NULL, ",");
            char *date = strtok(NULL, ",");

            if (sender != NULL && subject != NULL && date != NULL) {
                /* Copy each field into the fixed-size struct
                   buffers. NOTE: strcpy() does not check the
                   length of the source string, so a field longer
                   than its destination buffer would overflow it. */
                strcpy(email.sender, sender);
                strcpy(email.subject, subject);
                strcpy(email.date, date);

                email.priority = getPriority(email.sender);

                insert(&heap, email);
            }
        }

        /* NEXT command */
        else if (strcmp(line, "NEXT") == 0) {
            nextEmail(&heap);
        }

        /* READ command */
        else if (strcmp(line, "READ") == 0) {
            if (heap.size > 0)
                removeMax(&heap);
        }

        /* COUNT command */
        else if (strcmp(line, "COUNT") == 0) {
            printf("There are %d emails to read.\n", heap.size);
        }
        /* Any other line is silently ignored. */
    }

    /* Only close the file if we actually opened one (not stdin). */
    if (file != stdin)
        fclose(file);

    return 0;
}