/* ============================================================
 * EECS 348 Assignment 2
 * ------------------------------------------------------------
 * Program: gemini.c
 *
 * Description:
 *   Prioritizes a CEO's inbox using a MaxHeap implemented as a
 *   dynamically-growing, list-based (array-backed) heap. Emails
 *   are ranked first by sender category (Boss > Subordinate >
 *   Peer > ImportantPerson > OtherPerson > unrecognized) and,
 *   when two emails share a category, by date (the newer email
 *   wins). Commands are read one per line from a test file or
 *   from stdin:
 *       EMAIL <sender category>,<subject>,<date> - add an email
 *       NEXT                                     - show top email
 *       READ                                     - remove top email
 *       COUNT                                    - show # unread
 *
 * Inputs:
 *   argv[1] (optional) - path to a test file of commands. If no
 *   argument is given, commands are read from standard input.
 *
 * Output:
 *   Terminal output produced by NEXT and COUNT, in the exact
 *   Sender/Subject/Date and count format shown in the handout.
 *   An error message to stderr if the named file cannot be opened.
 *
 * Collaborators: None
 *
 * Other sources for the code:
 *   This file is the unmodified first draft generated by Gemini
 *   (Google), produced for comparison with a second,
 *   independently generated ChatGPT (OpenAI) draft.
 *
 * Author (comments added by): Cole Nola
 * Creation date: 09/17/2026
 * Revision date: September 17, 2026
 * ============================================================ */

#include <stdio.h>   /* for FILE, fopen, fgets, printf, sscanf, fprintf */
#include <stdlib.h>  /* for malloc, realloc, free */
#include <string.h>  /* for strcmp, strncpy, strtok, strcspn, strncmp */

/* Maximum length of one line of input read from the test file. */
#define MAX_LINE 256

/* ------------------------------------------------------------
 * Email
 *   One email message.
 *   sender          - sender CATEGORY string (e.g., "Boss")
 *   subject         - subject line (may contain spaces, not commas)
 *   date_str        - date string in MM-DD-YYYY format
 *   priority_score  - numeric priority derived from "sender"
 *   date_key        - date_str converted to a YYYYMMDD integer
 * ------------------------------------------------------------ */
typedef struct {
    char sender[32];
    char subject[128];
    char date_str[11];
    int priority_score;
    int date_key;
} Email;

/* ------------------------------------------------------------
 * MaxHeap
 *   A list-based (array-based) max-heap of Email records, using
 *   a heap-allocated array that grows as more emails arrive.
 *   data     - pointer to a dynamically-allocated array of Email
 *   size     - number of emails currently stored
 *   capacity - number of Email slots currently allocated
 * ------------------------------------------------------------ */
typedef struct {
    Email *data;
    int size;
    int capacity;
} MaxHeap;

// Maps sender category to numerical priority
/* ------------------------------------------------------------
 * get_sender_priority
 *   Maps a sender category string to a numeric priority score.
 * Input:  sender - the sender category string from the EMAIL line
 * Output: an integer priority from 0 (unrecognized) to 5 (highest)
 * ------------------------------------------------------------ */
int get_sender_priority(const char *sender) {
    if (strcmp(sender, "Boss") == 0) return 5;             /* read first */
    if (strcmp(sender, "Subordinate") == 0) return 4;      /* read next */
    if (strcmp(sender, "Peer") == 0) return 3;              /* read next */
    if (strcmp(sender, "ImportantPerson") == 0) return 2;   /* read next */
    if (strcmp(sender, "OtherPerson") == 0) return 1;        /* read last */
    return 0;  /* any unrecognized category ranks below OtherPerson */
}

// Converts MM-DD-YYYY into YYYYMMDD integer for easy chronological comparison
/* ------------------------------------------------------------
 * parse_date_key
 *   Converts an MM-DD-YYYY date string into a YYYYMMDD integer
 *   so two dates can be compared with a simple > check.
 * Input:  date_str - date string in MM-DD-YYYY format
 * Output: integer YYYYMMDD representation of the date
 * ------------------------------------------------------------ */
int parse_date_key(const char *date_str) {
    int month, day, year;
    /* Pull the three numeric fields out of "MM-DD-YYYY". */
    sscanf(date_str, "%d-%d-%d", &month, &day, &year);
    /* Combine into one comparable integer, year first. */
    return year * 10000 + month * 100 + day;
}

// Returns > 0 if email 'a' has higher priority than email 'b'
/* ------------------------------------------------------------
 * compare_emails
 *   Compares two emails for heap ordering.
 * Input:  a, b - the two emails being compared
 * Output: a positive value if a outranks b, negative if b
 *         outranks a, and 0 if they are equal in rank
 * ------------------------------------------------------------ */
int compare_emails(Email a, Email b) {
    if (a.priority_score != b.priority_score) {
        /* Different categories: the difference in score decides it. */
        return a.priority_score - b.priority_score;
    }
    // Newer date takes precedence
    /* Same category: fall back to comparing date keys, newer first. */
    return a.date_key - b.date_key;
}

/* ------------------------------------------------------------
 * create_heap
 *   Allocates a new, empty MaxHeap with room for
 *   initial_capacity emails.
 * Input:  initial_capacity - starting size of the backing array
 * Output: pointer to a heap-allocated MaxHeap
 * ------------------------------------------------------------ */
MaxHeap* create_heap(int initial_capacity) {
    MaxHeap *heap = (MaxHeap*)malloc(sizeof(MaxHeap));  /* allocate the struct */
    heap->capacity = initial_capacity;                    /* starting room */
    heap->size = 0;                                        /* heap starts empty */
    heap->data = (Email*)malloc(sizeof(Email) * heap->capacity);  /* allocate array */
    return heap;
}

/* ------------------------------------------------------------
 * swap
 *   Exchanges the contents of two Email structs in place.
 * ------------------------------------------------------------ */
void swap(Email *a, Email *b) {
    Email temp = *a;  /* stash a's value */
    *a = *b;           /* copy b's value into a */
    *b = temp;          /* copy the stashed original a into b */
}

/* ------------------------------------------------------------
 * heapify_up
 *   Restores the max-heap property by moving the email at
 *   "index" upward until its parent outranks it. Called right
 *   after a new email is appended to the array.
 * ------------------------------------------------------------ */
void heapify_up(MaxHeap *heap, int index) {
    while (index > 0) {
        int parent = (index - 1) / 2;  /* array-based parent formula */
        if (compare_emails(heap->data[index], heap->data[parent]) > 0) {
            /* Child outranks its parent: swap and keep climbing. */
            swap(&heap->data[index], &heap->data[parent]);
            index = parent;
        } else {
            /* Heap property holds; stop climbing. */
            break;
        }
    }
}

/* ------------------------------------------------------------
 * heapify_down
 *   Restores the max-heap property by moving the email at
 *   "index" downward, swapping with the higher-priority child,
 *   until neither child outranks it. Called after removal.
 * ------------------------------------------------------------ */
void heapify_down(MaxHeap *heap, int index) {
    while (1) {
        int left = 2 * index + 1;    /* array-based left-child formula */
        int right = 2 * index + 2;   /* array-based right-child formula */
        int largest = index;          /* assume current node wins for now */

        if (left < heap->size && compare_emails(heap->data[left], heap->data[largest]) > 0) {
            /* Left child actually outranks the current node. */
            largest = left;
        }
        if (right < heap->size && compare_emails(heap->data[right], heap->data[largest]) > 0) {
            /* Right child outranks whichever node is winning so far. */
            largest = right;
        }

        if (largest != index) {
            /* A child outranked the parent: swap down and keep sinking. */
            swap(&heap->data[index], &heap->data[largest]);
            index = largest;
        } else {
            /* Heap property holds; stop sinking. */
            break;
        }
    }
}

/* ------------------------------------------------------------
 * insert_email
 *   Adds a new email to the heap: doubles the backing array if
 *   it is full, places the email at the next free slot, then
 *   bubbles it up to its correct position.
 * ------------------------------------------------------------ */
void insert_email(MaxHeap *heap, Email email) {
    if (heap->size == heap->capacity) {
        /* Array is full: double its capacity and grow the block.
           NOTE: the return value of realloc() is not checked for
           NULL here, so an allocation failure would go unnoticed. */
        heap->capacity *= 2;
        heap->data = (Email*)realloc(heap->data, sizeof(Email) * heap->capacity);
    }
    heap->data[heap->size] = email;  /* place email at the end */
    heapify_up(heap, heap->size);     /* restore heap order */
    heap->size++;                      /* one more email is stored */
}

/* ------------------------------------------------------------
 * pop_max
 *   Removes the highest-priority (root) email. Does nothing if
 *   the heap is already empty.
 * ------------------------------------------------------------ */
void pop_max(MaxHeap *heap) {
    if (heap->size == 0) return;  /* nothing to remove */
    /* Move the last email into the root, then shrink the heap
       and sink the new root down to its proper place. */
    heap->data[0] = heap->data[heap->size - 1];
    heap->size--;
    heapify_down(heap, 0);
}

/* ------------------------------------------------------------
 * free_heap
 *   Releases all memory owned by the heap (the array and the
 *   MaxHeap struct itself).
 * ------------------------------------------------------------ */
void free_heap(MaxHeap *heap) {
    free(heap->data);  /* free the array of emails */
    free(heap);          /* free the heap struct */
}

/* ------------------------------------------------------------
 * main
 *   Reads commands from a file (argv[1]) or stdin, one per
 *   line, and dispatches each to the matching heap operation.
 * ------------------------------------------------------------ */
int main(int argc, char *argv[]) {
    MaxHeap *heap = create_heap(10);  /* start with room for 10 emails */
    char line[MAX_LINE];               /* buffer for one line of input */
    FILE *file = stdin;                 /* default to reading stdin */

    // Open sample.txt if passed via command line argument
    /* Use the file named on the command line if one was given. */
    if (argc > 1) {
        file = fopen(argv[1], "r");
        if (!file) {
            /* The named file could not be opened; report and bail out. */
            fprintf(stderr, "Error opening file: %s\n", argv[1]);
            free_heap(heap);
            return 1;
        }
    }

    /* Process the input one line at a time until end of file. */
    while (fgets(line, sizeof(line), file)) {
        // Strip trailing newline characters
        /* Strip the trailing newline (and any carriage return)
           so string comparisons work. */
        line[strcspn(line, "\r\n")] = 0;

        if (strncmp(line, "EMAIL ", 6) == 0) {
            Email e;
            char *payload = line + 6;  /* skip past "EMAIL " */

            // Parse comma-delimited string fields
            /* Split the remaining text on commas into its three
               fields: sender category, subject, and date.
               NOTE: strncpy() is bounds-checked, but it does not
               guarantee a trailing null terminator when the
               source string is at least as long as the copy
               limit, so an especially long field could leave the
               destination buffer unterminated. */
            char *token = strtok(payload, ",");
            if (token) strncpy(e.sender, token, sizeof(e.sender) - 1);

            token = strtok(NULL, ",");
            if (token) strncpy(e.subject, token, sizeof(e.subject) - 1);

            token = strtok(NULL, ",");
            if (token) strncpy(e.date_str, token, sizeof(e.date_str) - 1);

            e.priority_score = get_sender_priority(e.sender);
            e.date_key = parse_date_key(e.date_str);

            insert_email(heap, e);
        }
        else if (strcmp(line, "COUNT") == 0) {
            printf("There are %d emails to read.\n", heap->size);
        }
        else if (strcmp(line, "NEXT") == 0) {
            if (heap->size > 0) {
                Email top = heap->data[0];
                printf("Next email:\n");
                printf("Sender: %s\n", top.sender);
                printf("Subject: %s\n", top.subject);
                printf("Date: %s\n", top.date_str);
            }
            /* If the heap is empty, print nothing. */
        }
        else if (strcmp(line, "READ") == 0) {
            if (heap->size > 0) {
                pop_max(heap);
            }
        }
        /* Any other line is silently ignored. */
    }

    /* Only close the file if we actually opened one (not stdin). */
    if (file != stdin) {
        fclose(file);
    }

    free_heap(heap);  /* release all heap memory before exiting */
    return 0;
}